import uuid from 'uuid'

const storeFurnitures = [
    {
        id: uuid.v4(),
        title: "Craftmeister's Pine Bed",
        company: 'Crasper',
        category: 'bed',
        price: 276,
        img: 'img/bed1.png',
        info: 'Perhaps one of the best-known online mattress companies is Crasper, which offers three different mattress models, ranging in price from $600 to $1,850 for a queen size. One of the aspects that makes Crasper unique is that the brand has a dozen stores around the country where you can test out their mattresses before you buy.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Malm Bedframe',
        company: 'Phenix',
        category: 'bed',
        price: 262,
        img: 'img/bed2.png',
        info: 'If you want a mattress that’s tailored to your individual sleep preferences, you should look into Phenix, an online mattress retailer that customizes its products based on a short Sleep Quiz. Phenix even allows you to enter sleep preferences for your partner, and you can get a mattress that’s either blended to address both your sleep needs or that has two separate sleep zones.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Morissey Bed',
        company: 'Marble',
        category: 'bed',
        price: 298,
        img: 'img/bed3.png',
        info: 'You may have heard of Marble, an online mattress company that claims to have created an amazing new mattress to solve your sleep woes. The premise of Marble mattresses is that they support your back like a firm mattress but cradle your hips and shoulders like a soft mattress, giving you the best of both worlds.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Caress of Teak Bed',
        company: 'Neesa',
        category: 'bed',
        price: 237,
        img: 'img/bed4.png',
        info: 'If you’re looking for a high-quality memory foam mattress, you should check out Neesa, an online mattress retailer whose memory foam option has more than 10,000 5-star reviews — that’s a lot of happy customers!',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Country Sleeper',
        company: 'Luft & Feddles',
        category: 'bed',
        price: 291,
        img: 'img/bed5.png',
        info: 'One of the most budget-friendly options when it comes to buying a mattress online is Luft & Feddles. While this company only offers one style of mattress, you’ll be impressed with the quality of the product and the incredibly affordable price.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'The Four Post Bed',
        company: 'Ono',
        category: 'bed',
        price: 300,
        img: 'img/bed6.png',
        info: 'Can’t decide between a firm mattress or a soft one? With Ono, you don’t have to! This innovative mattress includes both soft and firm options — all you have to do is rotate the mattress 180 degrees to switch between the two.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Jules Visitors Chair',
        company: 'Grace',
        category: 'chair',
        price: 200,
        img: 'img/chair1.png',
        info: 'Comes with a foam and fibre seat cushion which gives support with low maintenance, while still allowing a comfy cushioned seat',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Patioplastics Chair',
        company: 'Think',
        category: 'chair',
        price: 235,
        img: 'img/chair2.png',
        info: 'Comes with foam-filled seat cushions for a beautiful look that bounces back - with no need to plump- Or choose our Contour Comfort Dual Layer Memory Foam cushions which respond to your body’s contours to provide the ultimate comfort and support (at extra cost)',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Floral Chair',
        company: 'Finsdale',
        category: 'chair',
        price: 269,
        img: 'img/chair3.png',
        info: 'Comes with foam-filled seat cushions for a beautiful look that bounces back - with no need to plump',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Chair da le mar',
        company: 'Wilson',
        category: 'chair',
        price: 229,
        img: 'img/chair4.png',
        info: 'Comes with a foam and fibre inner coil seat cushion which gives support with low maintenance, while still allowing a comfy cushioned seat',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Bowdacious Chair',
        company: 'Expression',
        category: 'chair',
        price: 208,
        img: 'img/chair5.png',
        info: 'A combination of 100% genuine leather on all the seating and comfort areas, with durable leather look fabric in other areas, which enables us to offer you the luxury of leather at an affordable price',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Oaktowne Chair',
        company: 'Witty',
        category: 'chair',
        price: 233,
        img: 'img/chair6.png',
        info: 'Comes with a foam and fibre seat cushion which gives support with low maintenance, while still allowing a comfy cushioned seat',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Numica Allinall Table',
        company: 'Tobitec',
        category: 'table',
        price: 213,
        img: 'img/table1.png',
        info: 'We are fully aware that projects can often be long-term undertakings and that every parameter is important. Accordingly, we work in real partnership with our fitter customers to offer them responsiveness, flexibility and advice. There is no doubt that our success is a result of yours.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Vika Table',
        company: 'MH Furnitures',
        category: 'table',
        price: 231,
        img: 'img/table2.png',
        info: 'Includes folding and stackable furniture (such as folding tables, folding chairs and stackable chairs) in various designs for the "major events service" market segment – specifically furniture rental companies – as well as banquet and conference furniture. ',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Pinegultcher Table',
        company: 'Dilani',
        category: 'table',
        price: 205,
        img: 'img/table3.png',
        info: 'Dilani has been a reference in Italy in the office chair and seat business for over 30 years. Simple craftwork in the beginning, the company has managed to maintain over time the same passion as when we started out.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Hula Feast Table',
        company: 'EFG Worldwide',
        category: 'table',
        price: 253,
        img: 'img/table4.png',
        info: 'From stackable chairs to tall bar tables made from top-quality materials, you will find exclusive, tried-and-tested yet appealing furniture that invites you to linger and enjoy the fare on offer whether indoors or outdoors. As is generally known, first impressions are some of the most important when it comes to attracting customers to your premises.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Myne Table',
        company: 'Large',
        category: 'table',
        price: 244,
        img: 'img/table5.png',
        info: "The majority of our product range can be delivered directly from stock, while precisely coordinated transport logistics also ensure excellent flexibility. Do you require a custom design or products that are not part of our standard range? Not a problem, don't hesitate to put us to the test!",
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Flatwood Table',
        company: 'Stapeler',
        category: 'table',
        price: 217,
        img: 'img/table6.png',
        info: 'Alongside purely classical or practical ranges are products that impress with their attractive appearance and distinctive features. However, the point of use should also be considered when deciding which stacking chairs to purchase; the customer can choose from a wide range of product variants, depending on application',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Malm Wardrobe',
        company: 'Hespoke',
        category: 'wardrobe',
        price: 207,
        img: 'img/wardrobe1.png',
        info: 'A Hespoke dressing room that’s beautifully tailored to your requirements could give your home extra storage, space and style. This modern design features an island of drawers with sumptuous seating, hand-built to suit our client’s needs. Open wardrobes and shelving with sleek, clean lines are made-to-measure, maximising every inch of wall space. The door and drawers are finished in a sophisticated neutral shade from our exclusive selection of paint colours.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Pit Stop Wardrobe',
        company: 'Stombury',
        category: 'wardrobe',
        price: 265,
        img: 'img/wardrobe2.png',
        info: 'A unique partnership of finishes creates a range of furniture that looks stunning in any area of the home. Shown here in a bedroom, it gives the room a feeling of decadence, alongside sumptuous bedding and our Henley upholstered bedhead. Thornbury is definitely a design for someone who appreciates the finer things in life and is looking for something a little out of the ordinary.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Fusty Hors Wardrobe',
        company: 'Descend',
        category: 'wardrobe',
        price: 289,
        img: 'img/wardrobe3.png',
        info: 'Our mess-free, hassle-free installation is carried out by polite professionals who take the utmost care of your home throughout the whole process.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Pompadour Wardrobe',
        company: 'Dwell',
        category: 'wardrobe',
        price: 295,
        img: 'img/wardrobe4.png',
        info: 'This luxury oak bedroom furniture is designed to cater for all storage needs whilst looking timeless and elegant. The range of bespoke storage options are perfect for storing all your clothing and accessories, with dedicated areas for each type of item to keep things organised and tidy. For example, the inclusion of a hidden shoe carousel and integrated tie rack ensure stylish, clutter free living, doing away with those annoying items that always end up at the end of the bed or strewn over the back of a chair.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Crustikus Wardrobe',
        company: 'Casandra',
        category: 'wardrobe',
        price: 213,
        img: 'img/wardrobe5.png',
        info: 'Transcending the boundaries of conventional bedroom storage, this exquisite dressing room has everything you could dream of and room for more. Every pair of shoes, every bracelet and necklace, every tie and cufflink all conveniently stored away. Hidden or on display, the choice is yours. From open shelving with integrated lights to pull out shoe racks with soft close mechanisms, you can have it all. When featured in our stunning White Larch finish, this dressing room is the epitome of indulgence.',
        inCart: false,
        count: 0,
        total: 0
    },
    {
        id: uuid.v4(),
        title: 'Anes Wardrobe',
        company: 'Lennigston',
        category: 'wardrobe',
        price: 219,
        img: 'img/wardrobe6.png',
        info: 'The Lenningston white dressing room is the ultimate in grandeur. Quintessentially British in style, extravagant mullions and imposing cornice detailing feature throughout to create an overall feeling of sumptuous luxury. Every proportion and detail has been considered, from carefully selected cut glass handles that shimmer in the light to smooth, soft close drawers with adjustable storage compartments for your precious jewels, nothing is left to chance.',
        inCart: false,
        count: 0,
        total: 0
    }
]

const detailFurniture = {
    id: uuid.v4(),
    title: "Craftmeister's Pine Bed",
    company: 'Crasper',
    category: 'bed',
    price: 276,
    img: 'img/bed1.png',
    info: 'Perhaps one of the best-known online mattress companies is Crasper, which offers three different mattress models, ranging in price from $600 to $1,850 for a queen size. One of the aspects that makes Crasper unique is that the brand has a dozen stores around the country where you can test out their mattresses before you buy.',
    inCart: false,
    count: 0,
    total: 0
}

export { storeFurnitures, detailFurniture }